### ISSUE TITLE
Shut up and take my money! (Or at least get it into CRAN)

### ISSUE THREAD

**Issue by LTLA** [hafen/rminiconda#5]
I have been exploring ways to reliably use Python code from Bioconductor packages (see my latest efforts [here](https://github.com/LTLA/basilisk)). Currently, the solution to guarantee that a given version of Python is available is to _download the Python sources and recompile them on the target machine_. This is about as disgusting as it sounds, especially on Windows.

If **rminiconda** were available on CRAN, we could just piggyback off the Python instance installed by **rminiconda**. There's still a little bit of work to do - we need to perform our own package version management on top - but it would make life a lot easier for us. Some testing indicates that it even solves our OpenSSL problem (LTLA/basilisk#1).

Also happy to push stuff the other way if any of our Python package management functionality in _basilisk_ seems useful to you... saves me from having to maintain another package...

**Comment by hafen** [comment]
Nice - I started down the path of compiling and gave up - you have more patience than I do!

It's good to see efforts like this and others (like #4). I'm not entirely certain about the future of this package (CRAN, etc.) since there is ongoing work to integrate this functionality into reticulate. If that ends up looking like a good universal solution then I'm happy to concentrate efforts there. However, if there is enough feedback that a separate package would be useful for other purposes, I'm open to that.

**Comment by LTLA** [comment]
Yes, based on discussions in LTLA/basilisk#2, it seems like this functionality might be provided in **reticulate** itself, in which case you're right - there wouldn't be a need for a separate package. 

Nonetheless, until that solution becomes available, I took the liberty of stealing the relevant parts of your code and sticking it into **basilisk**'s `configure` files. So it's getting some use, at least!
